### PR TITLE
Syntax Highlight

### PR DESCRIPTION
**Pull request by ghost**
Thought it might be interesting to add syntax highlight to editorconfig files.
I added this functionality if it makes sense for the project.

Syntax Highlight

### CODE REVIEW

**Comment by ghost** [comment]
@10sr Do you review the PR? See if it makes sense for the project or if you need to adjust something

**Review by 10sr — APPROVED** [review]
LGTM, thanks!

**Comment by ghost** [comment]
Cool, I'm going to delete my repository, I don't know if the pr code will continue to exist, so could you merge the code?

**Comment by 10sr** [comment]
~~OK, could you remove the changes related to releasing 1.1.0 ?
I'm going to release after merging #15 🙆 .~~

I'll merge #15 first so you don't need this 🙇

**Pull request merged**
